//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.06 at 12:08:30 PM KGT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://isagulova.kg/soapwebsocketproject/api/greeting", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package kg.isagulova.soapwebsocketproject.api.greeting;
